/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ygsj_jni3_JNIMethod */

#ifndef _Included_com_ygsj_jni3_JNIMethod
#define _Included_com_ygsj_jni3_JNIMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ygsj_jni3_JNIMethod
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ygsj_jni3_JNIMethod_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
